### PR TITLE
Resolve conflict with weight windows and global russian roulette

### LINKED ISSUE #2773: Weight windows while using survival biasing
## Bug Description

Turning on survival biasing significantly reduces the effectiveness of weight windows. First image is the neutron flux across a block with a weight window applied and survival biasing turned off. The second image is the neutron flux across the same block with a weight window applied and survival biasing turned on. 

image

image

## Steps to Reproduce

Having looked at the source code this appears to be caused by this if statement in the physics.cpp file:
```cpp
  // Play russian roulette if survival biasing is turned on
  if (settings::survival_biasing) {
    if (p.wgt() < settings::weight_cutoff) {
      russian_roulette(p, settings::weight_survive);
    }
  }
```

By default the settings::weight_cutoff is set to 0.25, so any particle which is split by the weight window to be below this value is rouletted. A work around a user can employ is to reduce the settings::weight_cutoff value. However, there is also a weight_window.cutoff value which limits the particles weight in the weight window routines and it would be better from a users point of view not to have two weight cutoff values which need to be set for different variance reduction games (and make weight windows less effective if not set properly).   

## Environment
Linux, OpenMC Version 0.14.0-dev

### PR DESCRIPTION
**Pull request by GuySten**
# Description

Currently the global neutron russian roulette (which is used when survival biasing is turned on) conflicts with the application of weight windows.
As suggested in https://github.com/openmc-dev/openmc/issues/2773#issuecomment-2881341409, this PR makes global neutron russian roulette apply only when neutrons are outside of the weight windows mesh boundaries.

Fixes #2773

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) (version 15) on any C++ source files (if applicable)
- [x] ~~I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)~~
- [x] ~~I have made corresponding changes to the documentation (if applicable)~~
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)

### CODE REVIEW

File: include/openmc/physics_common.h [hunk 1]
```diff
@@ -13,5 +13,9 @@ namespace openmc {
 //! \param[in] weight_survive Weight assigned to particles that survive
 void russian_roulette(Particle& p, double weight_survive);
 
+//! \brief Performs the global russian roulette operation for a neutron
```
Comment (pshriwise) [inline include/openmc/physics_common.h]: As far as this function is concerned, the particle type is irrelevant. I'd suggest renaming it to `apply_russian_roulette`.

```suggestion
//! \brief Performs the global russian roulette operation on a particle
```

File: src/physics_common.cpp [hunk 2]
```diff
@@ -18,4 +18,20 @@ void russian_roulette(Particle& p, double weight_survive)
   }
 }
 
+void apply_neutron_russian_roulette(Particle& p)
+{
+  // Play russian roulette if survival biasing is turned on
+  if (settings::survival_biasing) {
```
Comment (pshriwise) [inline src/physics_common.cpp]: to reduce nesting and increase readability in this function, let's start it with 

```c++
if (!settings::survival_biasing) return;
```

File: src/physics.cpp [hunk 3]
```diff
@@ -153,18 +153,10 @@ void sample_neutron_reaction(Particle& p)
...
-    if (settings::survival_normalization) {
-      if (p.wgt() < settings::weight_cutoff * p.wgt_born()) {
-        russian_roulette(p, settings::weight_survive * p.wgt_born());
-      }
-    } else if (p.wgt() < settings::weight_cutoff) {
-      russian_roulette(p, settings::weight_survive);
-    }
-  }
+  // Play russian roulette if there are no weight windows
+  if (!settings::weight_windows_on ||
```
Comment (pshriwise) [inline src/physics.cpp]: I think we may want to limit this to only the first condition. In the case that the weight window check points at collisions are disabled, I expect we'd see the same aggressive rouletting cited in #2773.

**Review by pshriwise — CHANGES_REQUESTED** [review]
Thanks @GuySten! You are a machine. Some thoughts to consider here in the comments.

File: src/physics.cpp (hunk 3 above)
Comment (GuySten) [reply src/physics.cpp]: The problem is that without that check we will not have global rouletting when we are outside the mesh boundary when collision checkpoints are disabled and surface checkpoints are enabled.

EDIT:
Maybe further restructure is needed.
I will think about that.

What do you think?

File: include/openmc/physics_common.h (hunk 1 above)
Comment (GuySten) [reply include/openmc/physics_common.h]: Done.

File: src/physics_common.cpp (hunk 2 above)
Comment (GuySten) [reply src/physics_common.cpp]: Done.

File: src/physics.cpp (hunk 3 above)
Comment (pshriwise) [reply src/physics.cpp]: If I'm understanding right, with weight windows on we'll still check for a valid weight window bin in `apply_weight_windows` and in the absence of a valid bin (i.e. if the particle is outside the mesh). 

It could be that particles exceed the lower or upper energy bounds of the weight windows rather than, but in essence I'd say this is equivalent to the argument about particles leaving the mesh -- if the user is interested in this energy space then it should be part of the weight windows definition.

Now, hypothetically, we could run into a problem where weight windows are enabled in the settings but all checkpoints are turned off, then no rouletting would apply. Maybe an extra initialization check/warning to address this would be a good idea.

Comment (GuySten) [reply src/physics.cpp]: If I understand correctly, If weight windows are on and collision checkpoints are off we will have global rouletting when outside of mesh only in surface checkpoints which is weird behavior.
Usually we use global rouletting only in collisions.

Comment (pshriwise) [reply src/physics.cpp]: It's different, true. Though the purpose of rouletting is that we address low-weight particles at some point in the simulation so they don't run for an exceedingly long amount of time, but I don't see a reason that this must occur during a collision event.

For infinite media problems we may never hit a surface to roulette these particles, but I also don't think we'd see application of weight windows in those cases.

That said, if you have a way of restructuring things so it aligns better with the current rouletting check points, I'm game! Main thing I'm watching out for is that we avoid an additional weight window look-up or additional particle state if possible, which your PR does well now.

**Comment by GuySten** [comment]
I've restructured the code to be more backwards compatible.

File: src/physics_mg.cpp [hunk 4]
```diff
@@ -31,8 +31,16 @@ void collision_mg(Particle& p)
   // Sample the reaction type
   sample_reaction(p);
 
-  if (settings::weight_window_checkpoint_collision)
-    apply_weight_windows(p);
+  if (settings::weight_windows_on) {
+    int mesh_bin;
+    const auto& ww = search_weight_window(p, mesh_bin);
```
Comment (pshriwise) [inline src/physics_mg.cpp]: I like the direction this is headed, but it feels a little clunky to me still. What if `search_weight_window` was allowed to return a null `WeightWindow` object? We could add a `mesh_bin` attribute to the `WeightWindow` object if needed.

**Comment by GuySten** [comment]
I've further improved the code structure according to your suggestion.
I will have to dig into why the tests fail.

File: src/physics.cpp [hunk 5]
```diff
@@ -61,8 +61,15 @@ void collision(Particle& p)
     break;
   }
 
-  if (settings::weight_window_checkpoint_collision)
-    apply_weight_windows(p);
+  if (settings::weight_windows_on) {
+    auto ww = search_weight_window(p);
+    if (ww.is_valid()) {
+      if (settings::weight_window_checkpoint_collision)
```
Comment (pshriwise) [inline src/physics.cpp]: We probably want to move this check up before searching for the weight window so we don't do a search and then discard the weight window without using it.

Comment (GuySten) [reply src/physics.cpp]: We actually want to do the search anyway because if we are outside the mesh domain we need to do global russian roulette.

Comment (GuySten) [reply src/physics.cpp]: Actually, I can improve performance a bit by only doing the search if the particle type is a neutron.
I will try that.

**Comment by GuySten** [comment]
This PR is now ready for another review iteration.

File: src/physics.cpp [hunk 6]
```diff
@@ -61,8 +61,25 @@ void collision(Particle& p)
     break;
   }
 
-  if (settings::weight_window_checkpoint_collision)
-    apply_weight_windows(p);
+  if (settings::weight_windows_on) {
```
Comment (pshriwise) [inline src/physics.cpp:67]: I took a crack at simplifying this a bit further [here](https://github.com/openmc-dev/openmc/commit/60be00575468edbe7c4aa0f86655281b08c20f87)

Take a look and see if you think that covers the intended cases here.

File: src/weight_windows.cpp [hunk 7]
```diff
@@ -372,26 +270,34 @@ void WeightWindows::set_mesh(const Mesh* mesh)
   set_mesh(model::mesh_map[mesh->id_]);
 }
 
-WeightWindow WeightWindows::get_weight_window(const Particle& p) const
+const int WeightWindows::get_mesh_bin(const Particle& p) const
```
Comment (pshriwise) [inline src/weight_windows.cpp]: After the latest refactor, do we still need this method? I think placing some of the checks on particle state differently could allow us to remove it.

**Review by pshriwise — CHANGES_REQUESTED** [review]
I think we're getting closer here. I made a suggestion for simplified logic in the collision functions.

There are also some checks on particle state inside `get_mesh_bin` that feel a little out of place. Not incorrect really, but the don't seem to fit into the purpose of that function. There might be some further refactoring we can to to make that a little cleaner.

File: src/physics.cpp (hunk 6 above)
Comment (GuySten) [reply src/physics.cpp:67]: Your code is a lot more readable which is a plus.
The difference is only if we calculate weight windows in the case where weight windows are on collision checkpoint is off and the particle is a photon.

I think that case is not that common and readability should win so I will update this PR.

File: src/weight_windows.cpp (hunk 7 above)
Comment (GuySten) [reply src/weight_windows.cpp]: I've removed it.

**Comment by GuySten** [comment]
@pshriwise, I've incorporated your suggestions and this PR is ready to review.

**Comment by pshriwise** [comment]
After some testing, there's more work to be done here to clarify the difference between a weight window that is not found and the case where a weight window is found but unset. I'll add a post here with a solution later today.

**Comment by pshriwise** [comment]
I tried applying this to a similar problem to the one presented in #2773. It's  a block of Tungsten with an incident planar source of neutrons. All boundaries are reflective except the positive X plane, which is a vacuum boundary condition. These are short runs with 10k particles, 10 batches.

When I tried it as of 57b5d27, the survival biasing was still limiting the effectiveness of the weight windows because _unset_ weight windows (different from the search for a weight window failing) were also resulting in `WeightWindow::is_valid` returning false and pushing us into the all to `apply_russian_roulette`. I'm glad I was using the MAGIC method for weight window generation in this case or I likely wouldn't have noticed this!

At any rate, what we need to separate here is the cases where a weight window is unset in the `WeightWindows` object vs. not being able to find one due to energy limits, a particle being outside the mesh, etc. The latest commit I pushed here takes care of that with an extra flag emitted from `search_weight_window` and `get_weight_window`. Happy to discuss the design of that further, but from the images below we can see we're now getting the effect we desire.


Weight windows, no survival biasing (same in 57b5d27 and a53c066)

image


Weight windows w/ survival biasing on 57b5d27

ww-survival


Weight windows w/ survival biasing on, a53c0669

image

**Comment by GuySten** [comment]
@pshriwise, can you add the last test (weight windows w/ survival biasing) as a regression test?

**Comment by pshriwise** [comment]
> @pshriwise, can you add the last test (weight windows w/ survival biasing) as a regression test?

Yeah that's good call. I'm hesitant to make it a regression test as it's going to be pretty sensitive to the prn stream. I'm thinking at least a coarse check that turning on survival biasing at least doesn't reduce the number of mesh bins with tallied results. I can't think of a reason that it would.

I'll also look into the now-failing regression test. Something must be different with the control flow without survival biasing on now.

**Comment by pshriwise** [comment]
Okay I finally had some time to dig into the failing test and I found, well, a number of things.

First, I noted that if I omitted the photon weight windows from the regression test that it would pass on both `develop` and this branch. Then I realized that there are actually two sets of neutron weight windows in that test (which I've corrected in #3798) and this was partially the cause of the problem. In the previous `apply_weight_window` function we weren't differentiating between a weight window not being found and one being unset, so in the loop searching for a weight window

https://github.com/openmc-dev/openmc/blob/96383fcb2bb40da733b55241779ce75d2d9ab9c3/src/weight_windows.cpp#L69-L76

it would note the weight window isn't valid (now what we consider to be unset) and continue to search in the second set of weight windows, sometimes finding a valid window to use. Now that we accept a weight window if it is unset or not, this changes the behavior of the test case -- but only because there are two overlapping sets of neutron weight windows! So, as I mentioned before I've corrected this test in #3798. 

It's not really valid to have overlapping sets of weight windows like that. We may want to enforce that only one set of weight windows is allowed per particle type, but I don't want to rule out any creative use cases of multiple (non-overlapping) weight window meshes either.

tl;dr: once #3798 goes in, we should be able to update this branch and expect tests to pass.

**Comment by GuySten** [comment]
@pshriwise, now the only thing missing is to turn your tungsten model into a unit test where we check that more bins are scored to with weight windows and survival biasing compared to weight windows alone.

**Review by pshriwise — CHANGES_REQUESTED** [review]
Everything looks good after the updates. Placing a hold here for a bit while I look at a couple more test scenarios.

**Comment by GuySten** [comment]
@pshriwise, did you find any problems?

**Comment by pshriwise** [comment]
All looks good to me! Thanks for your patience. I'll ping others in the motivating issue asking for confirmation that our changes work.

**Review by pshriwise — APPROVED** [review]
