### PR TITLE
Fixed a bug in distribcell offsets logic

### LINKED ISSUE #3462: Bug in openmc distribcell offsets tables
## Bug Description

Openmc crash on some inputs when using distrimats because of wrong distribmat offset tables.

## Steps to Reproduce

```
import numpy as np
import openmc


model = openmc.model.Model()

uo2 = openmc.Material(name='UO2')
uo2.set_density('g/cm3', 10.0)
uo2.add_nuclide('U235', 1.0)
uo2.add_nuclide('O16', 2.0)
water = openmc.Material(name='light water')
water.add_nuclide('H1', 2.0)
water.add_nuclide('O16', 1.0)
water.set_density('g/cm3', 1.0)
water.add_s_alpha_beta('c_H_in_H2O')
model.materials.extend([uo2, water])

cyl = openmc.ZCylinder(r=0.4)
pin = openmc.model.pin([cyl], [uo2, water])
d = 1.0
    
lattice00 = openmc.RectLattice()
lattice00.lower_left = (-d, -d)
lattice00.pitch = (d, d)
lattice00.outer = pin
lattice00.universes = [[pin]]
box00 = openmc.model.RectangularPrism(d, d, origin=(-d/2,-d/2))
    
lattice01 = openmc.RectLattice()
lattice01.lower_left = (-d, 0)
lattice01.pitch = (d, d)
lattice01.outer = pin
lattice01.universes = [[pin]]
box01 = openmc.model.RectangularPrism(d, d, origin=(-d/2,d/2))
    
lattice10 = openmc.RectLattice()
lattice10.lower_left = (0, -d)
lattice10.pitch = (d, d)
lattice10.outer = pin
lattice10.universes = [[pin]]
box10 = openmc.model.RectangularPrism(d, d, origin=(d/2,-d/2))
    
lattice11 = openmc.RectLattice()
lattice11.lower_left = (0, 0)
lattice11.pitch = (d, d)
lattice11.outer = pin
lattice11.universes = [[pin]]
box11 = openmc.model.RectangularPrism(d, d, origin=(d/2,d/2))
    
    
cell00 = openmc.Cell(fill=lattice00, region = -box00)
cell01 = openmc.Cell(fill=lattice01, region = -box01)
cell10 = openmc.Cell(fill=lattice10, region = -box10)
cell11 = openmc.Cell(fill=lattice11, region = -box11)
    
univ = openmc.Universe(cells=[cell00, cell01, cell10, cell11])
    
box = openmc.model.RectangularPrism(2*d, 2*d, boundary_type='reflective')

main_cell = openmc.Cell(fill=univ, region=-box)
model.geometry = openmc.Geometry([main_cell])
model.geometry.merge_surfaces = True
   
model.settings.batches = 10
model.settings.inactive = 5
model.settings.particles = 1000
   
model.differentiate_mats(depletable_only=False) # necessary for crash

model.run()
```

## Environment

latest develop branch, test nuclear data.

## Solution
I opened pr #3424, to fix this problem.
I hope that now with a MWE it will get more attention.

### PR DESCRIPTION
**Pull request by GuySten**
# Description

This pr fixes a bug in distribcell offset logic.

I have added checks that distribcell paths are unique for every distribcell instance.

I then changed the distribcell offset logic to pass all regression tests and the new added checks.

closes shaikinast/SPERT#8

closes #3462 

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) (version 15) on any C++ source files (if applicable)
- [x] I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)

### CODE REVIEW

**Comment by lewisgross1296** [comment]
What exactly was going wrong here / do you have a test or MWE that shows the change in behavior? Going from incorrect to correct behavior, for example.

I think I remember having issues with Distribcell Filters in the past and am curious if this is related. If there's an existing issue related to this PR, it would be good to have a Closes #ISSUE as well.

**Comment by GuySten** [comment]
> What exactly was going wrong here / do you have a test or MWE that shows the change in behavior? Going from incorrect to correct behavior, for example.
> 
> I think I remember having issues with Distribcell Filters in the past and am curious if this is related. If there's an existing issue related to this PR, it would be good to have a Closes #ISSUE as well.

I found the issue by debugging why a huge reactor model crashed when using distribmats.
I traced the bug to the fact that in that model the function cell_instance_at_level from geometry.cpp returned a value that is bigger than the total number of instances (obviously wrong behaviour).
I then discovered that the function distribcell_path crashes sometimes so I included a (failing) check that for every distribcell instance a unique distribcell_path can be computed.
I then fixed the logic to make this check work and to pass all the rest of the regression tests.

The fact that the regression tests pass with my added check (that was initially failing) is the proof that the implementation is correct.

**Comment by lewisgross1296** [comment]
Neat, glad you were able to get past your issue and uncover something that was going wrong.

I asked about tests because I didn't see an added test in the `Files changed` tab and I'm not quite sure I see where the regression tests were failing on Github Actions (at least for this PR, attached a screenshot of the only two instances of this PR in the GHA tab)
Screenshot 2025-06-02 at 7 46 19 PM

Was it a local failure for the regression test that you were experiencing?

**Comment by GuySten** [comment]
> Neat, glad you were able to get past your issue and uncover something that was going wrong.
> 
> I asked about tests because I didn't see an added test in the `Files changed` tab and I'm not quite sure I see where the regression tests were failing on Github Actions (at least for this PR, attached a screenshot of the only two instances of this PR in the GHA tab) Screenshot 2025-06-02 at 7 46 19 PM
> 
> Was it a local failure for the regression test that you were experiencing?

I had local regression tests failing after adding the lines:
https://github.com/openmc-dev/openmc/blob/6eab5dbdee234d104b974b7006d03cb39a4cc688/src/geometry_aux.cpp#L434C1-L455C2

Specifically I remember that the distribmat regression test was failing after adding the check above.

**Comment by GuySten** [comment]
@pshriwise, you have access to shaikinast/SPERT#8 so maybe you can review this pr?

File: src/geometry_aux.cpp [hunk 1]
```diff
@@ -378,13 +379,17 @@ void prepare_distribcell(const std::vector<int32_t>* user_distribcells)
...
   // Search through universes for material cells and assign each one a
   // unique distribcell array index.
-  int distribcell_index = 0;
   vector<int32_t> target_univ_ids;
   for (const auto& u : model::universes) {
     for (auto idx : u->cells_) {
       if (distribcells.find(idx) != distribcells.end()) {
-        model::cells[idx]->distribcell_index_ = distribcell_index++;
-        target_univ_ids.push_back(u->id_);
+        if (std::find(target_univ_ids.begin(), target_univ_ids.end(), u->id_) ==
```
Comment (pshriwise) [inline src/geometry_aux.cpp]: Is this set of changes truly of consequence? What this section of code is/was doing is assigning a unique index for each cell so that the location of the offset in universe offset arrays and lattice tables is associated with that particular cell.

Given that we're looping over all universes in the problem here and a cell can't be used in more than one universe, this effectively re-shuffles those indices but I don't think the change will be of consequence other than a new ordering of the instance offsets.

File: src/geometry_aux.cpp [hunk 2]
```diff
@@ -420,7 +425,29 @@ void prepare_distribcell(const std::vector<int32_t>* user_distribcells)
           c.offset_[map] = offset;
           Lattice& lat = *model::lattices[c.fill_];
           offset +=
-            lat.fill_offset_table(offset, target_univ_id, map, univ_count_memo);
+            lat.fill_offset_table(0, target_univ_id, map, univ_count_memo);
```
Comment (pshriwise) [inline src/geometry_aux.cpp]: This change looks problematic to me. This essentially means that the lattice tables are going to produce the same set of instance values even if the lattice is used more than once in the model. 

For example, in the MWE you provided (thank you for that!) if you reuse one of the lattices and then apply a cell instance filter you'll find that one of the instances has a zero tally value where it doesn't if each lattice is used once.

MWE geometry as provided:

``` ============================>     TALLY 1     <============================

 Distributed Cell u7->c7->u6->c3->l2(0,0)->u1->c1
   Total Material
     Flux                                 2.65787 +/- 0.0208295
 Distributed Cell u7->c7->u6->c4->l3(0,0)->u1->c1
   Total Material
     Flux                                 2.67515 +/- 0.0464091
 Distributed Cell u7->c7->u6->c5->l4(0,0)->u1->c1
   Total Material
     Flux                                 2.67412 +/- 0.0405048
 Distributed Cell u7->c7->u6->c6->l5(0,0)->u1->c1
   Total Material
     Flux                                 2.73 +/- 0.0568137
```

MWE geometry using:

```
cell00 = openmc.Cell(fill=lattice00, region = -box00)
cell01 = openmc.Cell(fill=lattice01, region = -box01)
cell10 = openmc.Cell(fill=lattice10, region = -box10)
cell11 = openmc.Cell(fill=lattice10, region = -box11) # reuse lattice10
```

```
 ============================>     TALLY 1     <============================

 Distributed Cell u7->c7->u6->c3->l2(0,0)->u1->c1
   Total Material
     Flux                                 5.38786 +/- 0.0681062
 Distributed Cell u7->c7->u6->c4->l3(0,0)->u1->c1
   Total Material
     Flux                                 2.67515 +/- 0.0464091
 Distributed Cell u7->c7->u6->c5->l4(0,0)->u1->c1
   Total Material
     Flux                                 2.67412 +/- 0.0405048
 Distributed Cell u7->c7->u6->c6->l4(0,0)->u1->c1
   Total Material
     Flux                                 0 +/- 0
```

File: src/geometry_aux.cpp [hunk 3]
```diff
@@ -420,7 +425,29 @@ void prepare_distribcell(const std::vector<int32_t>* user_distribcells)
...
+        }
+      }
+    }
+  }
+
+  // check distinct distribcell paths from contiguous cell instances
+  for (const auto& u : model::universes) {
```
Comment (pshriwise) [inline src/geometry_aux.cpp]: I like this check, though I might suggest we make it optional as this could be very expensive for larger models. 

Also, was this intended to catch the problem produced in the MWE? When I run the example I still get to transport before failure.

File: src/geometry_aux.cpp [hunk 4]
```diff
@@ -570,12 +594,12 @@ std::string distribcell_path_inner(int32_t target_cell, int32_t map,
     path << "l" << lat.id_;
     for (ReverseLatticeIter it = lat.rbegin(); it != lat.rend(); ++it) {
       int32_t indx = lat.universes_.size() * map + it.indx_;
-      int32_t temp_offset = offset + lat.offsets_[indx];
-      if (temp_offset <= target_offset - c.offset_[map]) {
+      int32_t temp_offset = offset + lat.offsets_[indx] + c.offset_[map];
```
Comment (pshriwise) [inline src/geometry_aux.cpp:540]: I like the removal of the operator in the conditional that results from this. The one in the call to `distribcell_path_inner` below as well. It's more clear. Thanks!

**Review by pshriwise — COMMENTED** [review]
Hi @GuySten! Thanks for looking into this! And thank you very much for the MWE -- incredibly helpful.

I have a few questions regarding the changes here. This section of code is particularly esoteric unfortunately and pretty sensitive to changes, so we'll want to be cautious about how to address this issue.

In addition to the MWE, I'll look at the full reactor model you linked earlier as well to gather more information as to the root cause of the problem you're seeing there. Any insights you have to add are more than welcome also of course!

File: src/geometry_aux.cpp (hunk 1 above)
Comment (GuySten) [reply src/geometry_aux.cpp]: This change make cells that are contained in the same universe share distribcell_index. So this is an optimization.
This optimization is important when a universe contains alot of cells.
I updated the comment to reflect this change.

File: src/geometry_aux.cpp (hunk 2 above)
Comment (GuySten) [reply src/geometry_aux.cpp]: I am pretty confident that this change is necessary.

When you reuse the lattice I suspect that the boundaries are not aligned with the new location so you hit lattice.outer and you get 0 flux tally.

File: src/geometry_aux.cpp (hunk 3 above)
Comment (GuySten) [reply src/geometry_aux.cpp]: This check was indeed intended to catch the problem in the MWE.

By using openmc-plotter you can see that instance numbers are not contiguous.

The change:

lat.fill_offset_table(offset, target_univ_id, map, univ_count_memo); -> lat.fill_offset_table(0, target_univ_id, map, univ_count_memo);

is the most important change in this whole pr.

Without it the cell instances are not contiguous and this check fails.

Comment (GuySten) [reply src/geometry_aux.cpp]: I support making this check optional only if you have a concrete example where this takes a non negligible fraction of runtime.

File: src/geometry_aux.cpp (hunk 1 above)
Comment (pshriwise) [reply src/geometry_aux.cpp]: Ah yes yes you're right. Thanks. Should save space for the distribcell arrays if all else is populated correctly.

File: src/geometry_aux.cpp (hunk 2 above)
Comment (pshriwise) [reply src/geometry_aux.cpp]: Mmmm yeah I believe that's correct. Still a red flag here that the flux in the first cell instance is twice as high. Quite posible that's a pre-existing issue though -- instance tally contributions for cells in `lattice.outer` appear to be going to the first cell instance by default.

File: src/geometry_aux.cpp (hunk 3 above)
Comment (pshriwise) [reply src/geometry_aux.cpp]: > This check was indeed intended to catch the problem in the MWE.

When I run the MWE this check doesn't seem to catch a problem with contiguity in the cell instances. Should we look into that?

> lat.fill_offset_table(offset, target_univ_id, map, univ_count_memo); -> lat.fill_offset_table(0, target_univ_id, map, univ_count_memo);

Yes, with the context you provided above as to the optimization of the distribcell indices this makes sense. I'll spend some time thinking it through some more now that the intention is more clear to me.

Comment (pshriwise) [reply src/geometry_aux.cpp]: > I support making this check optional only if you have a concrete example where this takes a non negligible fraction of runtime.

Fair enough. I'll look into an example.

Comment (GuySten) [reply src/geometry_aux.cpp]: > When I run the MWE this check doesn't seem to catch a problem with contiguity in the cell instances. Should we look into that?

I suspect you have some user error. When I run the MWE in a custom branch with this check enabled the code crash on this check.

File: src/geometry_aux.cpp (hunk 2 above)
Comment (pshriwise) [reply src/geometry_aux.cpp]: Okay same page here now. Given that this is the only place we call `fill_offset_table` and we're hardcoding the first argument to zero, let's remove that argument from the method itself.

File: src/geometry_aux.cpp (hunk 3 above)
Comment (pshriwise) [reply src/geometry_aux.cpp]: I'm putting together some info on how this block affects initialization times for things like TRISO problems, but it's a nice check to have whether it's optional or not.

Separately, I'm not a huge fan of the string comparisons here thought I understand that's kind of what we have to work with at the moment. I'd rather see these comparisons performed on an object that represents the path -- a collection of `LocalCoord` or the like. Not a trivial change I know, but I'm pretty hesitant to include it without a different option for comparison of the paths.

**Comment by GuySten** [comment]
> Based on the MWE you made, it could be reuse of the same universe in different lattices. Is that right?

I arrived at the MWE based on the assumption that it is true. So I suspect that it is right.

File: src/geometry_aux.cpp (hunk 2 above)
Comment (GuySten) [reply src/geometry_aux.cpp]: Done.

I suspect that in a future PR (fixing lattice.outer behaviour) we might need this argument back.
But then we can revert this change.

File: src/geometry_aux.cpp (hunk 3 above)
Comment (GuySten) [reply src/geometry_aux.cpp]: > Separately, I'm not a huge fan of the string comparisons here thought I understand that's kind of what we have to work with at the moment. I'd rather see these comparisons performed on an object that represents the path -- a collection of `LocalCoord` or the like. Not a trivial change I know, but I'm pretty hesitant to include it without a different option for comparison of the paths.

Your description is a bit vague for me to implement it and I do not see an immediate need for this change.
Maybe you could approve this PR and afterwards open a new PR with your proposed changes?

Alternatively if you insist, we can delay merging this PR until you implement this alternative data structure.

I prefer the first option because, as you said, your suggestion is for a non trivial change.

If you want you can add another maintainer to the discussion and we can hear their opinion.

Comment (pshriwise) [reply src/geometry_aux.cpp]: I don't have a perfect picture of what it might look like quite yet. And I could've been more clear, I wouldn't necessarily expect you to implement such a change.

What I'd like to do is separate concerns here and get the fix merged in and add this check in a separate PR where we can discuss its implementation and whether or not it should be optional/default/enforced if you're open to that.

---

Going back to initialization time effects of this check, I ran this through a couple of models:

**BEAVRS benchmark (model repo [here](https://github.com/mit-crpg/BEAVRS)):**

Without check: 4.5s
With check: 50s

**Gas cooled TRISO assembly problem (image below)**

Without check: 4m 30s
With check: >3h

assembly
assembly_zoomed

The various colors in the fuel channels are a search lattice we employ to accelerate point containment searches in these types of models -- this is where I expect a lot of time is being spent in the check.

Probably worth noting that I did update the `paths` variable from a `std::set` to a `std::unordered_set` for the O(1) lookup time in the `find` call.

@paulromano if you don't mind chiming in with your thoughts when you have time, that would be most welcome!

**Comment by pshriwise** [comment]
> I thought about another simplification to the distribcell logic. We can make cell.n_instances a function that will call universe.n_instances and store universe instance count instead of cell instance count. This optimization will reduce storage of instance numbers when there are alot of cells.
> 
> @pshriwise, If you think it is worthwhile I can implement it in this pr.

I like it! I'll suggest we come to a resolution on some other things in this PR first, but I'd like to revisit for sure.

File: src/geometry_aux.cpp (hunk 3 above)
Comment (GuySten) [reply src/geometry_aux.cpp]: > What I'd like to do is separate concerns here and get the fix merged in and add this check in a separate PR where we can discuss its implementation and whether or not it should be optional/default/enforced if you're open to that.

That is a good idea. After seeing the difference in time berween with and without the check I have to agree that the check should not be enforced without the option to turn it off.
As you said, In a seperate PR we can explore different data structure for comparison but in my opinion it is more important to decide when to turn the check on (maybe only in geometry debug mode?) and we can also try to parallelize it using omp.
Your test cases are really useful for time testing this feature!

I will move this check to a draft PR and clean this PR.

Edit:
I removed the check and cleaned this PR.

**Comment by GuySten** [comment]
> > I thought about another simplification to the distribcell logic. We can make cell.n_instances a function that will call universe.n_instances and store universe instance count instead of cell instance count. This optimization will reduce storage of instance numbers when there are alot of cells.
> > @pshriwise, If you think it is worthwhile I can implement it in this pr.
> 
> I like it! I'll suggest we come to a resolution on some other things in this PR first, but I'd like to revisit for sure.

In my last commit I removed Cell.n_instances and now it resides in model::universe_counts.

**Comment by GuySten** [comment]
I think that this PR is ready or nearly ready to be merged.
@pshriwise , do you agree?

File: src/geometry_aux.cpp [hunk 5]
```diff
@@ -356,35 +345,39 @@ void prepare_distribcell(const std::vector<int32_t>* user_distribcells)
...
-  int distribcell_index = 0;
+  // distribcell array index according to the containing universe.
   vector<int32_t> target_univ_ids;
   for (const auto& u : model::universes) {
     for (auto idx : u->cells_) {
       if (distribcells.find(idx) != distribcells.end()) {
-        model::cells[idx]->distribcell_index_ = distribcell_index++;
-        target_univ_ids.push_back(u->id_);
+        if (std::find(target_univ_ids.begin(), target_univ_ids.end(), u->id_) ==
+            target_univ_ids.end()) {
```
Comment (pshriwise) [inline src/geometry_aux.cpp]:
```suggestion
        if (contains(target_univ_ids, u->id_)) {
```

File: include/openmc/geometry_aux.h [hunk 6]
```diff
@@ -15,8 +15,7 @@
 namespace openmc {
 
 namespace model {
-extern std::unordered_map<int32_t, std::unordered_map<int32_t, int32_t>>
-  universe_cell_counts;
+extern std::unordered_map<int32_t, int32_t> universe_counts;
```
Comment (pshriwise) [inline include/openmc/geometry_aux.h]: I think my preference would be to store this information on the `Universe` objects themselves. Each cell can lookup this information on the universe using the universe index stored on the `Cell` class.


```cpp
int32_t Cell::n_instances() const
{
  return model::universes[universe_]->n_instances_;
}

```

File: src/geometry_aux.cpp (hunk 5 above)
Comment (GuySten) [reply src/geometry_aux.cpp]: Done.

File: include/openmc/geometry_aux.h (hunk 6 above)
Comment (GuySten) [reply include/openmc/geometry_aux.h]: Done.

**Review by pshriwise — APPROVED** [review]
Looks good @GuySten! Thanks for these improvements in the cell instance data structures! I do want to look at it one more time, but barring any other issues I'll merge in the next 24h or so.

File: include/openmc/geometry_aux.h [hunk 7]
```diff
@@ -15,8 +15,6 @@
 namespace openmc {
 
 namespace model {
-extern std::unordered_map<int32_t, std::unordered_map<int32_t, int32_t>>
```
Comment (aprilnovak) [inline include/openmc/geometry_aux.h:18]: I am trying to update Cardinal to the latest version of OpenMC; we were relying on this variable. Can you please recommend an alternative for us now that it has been deleted?

Comment (GuySten) [reply include/openmc/geometry_aux.h:18]: Your request will be easier if you would provide the context in which this variable is used in Cardinal.

Can you link the places in Cardinal where it is used?

Comment (aprilnovak) [reply include/openmc/geometry_aux.h:18]: Sorry for the false alarm - when I looked closer to get this information, it appears that we can live without this variable. Thank you!
