### PR TITLE
Fix #2994, non-existent path causes segmentation fault when saving plot 

### LINKED ISSUE #2994: Error message when plot `filename` path does not exist
## Description
If you inadvertently provide a `filename` when generating plots, which does not exist on your machine (e.g., a typo in a full path), OpenMC will seg fault.

```
 Processing plot 1:
 /data/repo/outputs/analysis_pipeline/openmc/bol/hot_bol/plot_1.png...
Segmentation fault (core dumped)
```

## Alternatives
Check if file path exists before trying to write there.

## Compatibility
Improved user experience.

### PR DESCRIPTION
**Pull request by pitkajuh**
# Description

As stated in the bug report, a segmentation fault happens when trying to create a plot with non-existent path in plot.xml. This pull request fixes the issue.

Fixes #2994

# Checklist

- [X] I have performed a self-review of my own code
- [X] I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) (version 15) on any C++ source files (if applicable)
- [ ] I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)

### CODE REVIEW

File: src/plot.cpp [hunk 1]
```diff
@@ -315,6 +315,11 @@ void Plot::set_output_path(pugi::xml_node plot_node)
   } else {
     filename = fmt::format("plot_{}", id());
   }
+  const std::string dir_if_present =
+    filename.substr(0, filename.find_last_of("/") + 1);
+  if (!dir_exists(dir_if_present) and dir_if_present.size() > 0) {
```
Comment (pshriwise) [inline src/plot.cpp:320]: Performing the simple check first for short-circuit of the logical expression.

```suggestion
  if (dir_if_present.size() > 0 && !dir_exists(dir_if_present)) {
```

**Review by pshriwise — CHANGES_REQUESTED** [review]
A clear improvement. Thanks @pitkajuh! Really small suggestion here but then I think it's good to go.

**Comment by pshriwise** [comment]
@pitkajuh I've just added a test to ensure this works as expected. Let me know if that looks alright to you.

**Review by paulromano — APPROVED** [review]

**Review by pshriwise — APPROVED** [review]
