### PR TITLE
Fix negative distances from bins_crossed for CylindricalMesh

### LINKED ISSUE #3369: Negative scores with CylindricalMesh filter
## Bug Description

@rossmacdonald98  and I recently noticed negative values in a tally with a CylindricalMesh filter.
Also discussed this with @pshriwise 

Code available [here](https://github.com/LIBRA-project/BABY-LiOx/blob/neutronics/analysis/neutron/openmc_model_LiOx.py)

```
Tally
	ID             =	1
	Name           =	TBR
	Filters        =	CellFilter, MeshFilter
	Nuclides       =	total
	Scores         =	['(n,Xt)']
	Estimator      =	tracklength
	Multiply dens. =	True
No. radial bins (x) 28
No. angular bins (y) 2
No. axial bins (z) 26
Dataframe:
     cell mesh 1        nuclide   score      mean std. dev.
               x  y   z                                    
0       7      1  1   1   total  (n,Xt)  4.66e-07  1.20e-07
1       7      2  1   1   total  (n,Xt) -1.60e-04  1.52e-04
2       7      3  1   1   total  (n,Xt) -5.71e-06  1.50e-05
3       7      4  1   1   total  (n,Xt) -2.46e-05  2.86e-05
4       7      5  1   1   total  (n,Xt) -7.69e-05  8.44e-05
...   ...    ... ..  ..     ...     ...       ...       ...
1451    7     24  2  26   total  (n,Xt) -7.24e-04  4.54e-04
1452    7     25  2  26   total  (n,Xt) -3.01e-03  1.27e-03
1453    7     26  2  26   total  (n,Xt) -5.95e-04  2.97e-04
1454    7     27  2  26   total  (n,Xt) -1.93e-03  8.04e-04
1455    7     28  2  26   total  (n,Xt) -1.79e-02  1.31e-02
```

## Steps to Reproduce

- n,Xt score
- CylindricalMeshFilter tally with offset mesh origin

## Environment

[Environment file](https://github.com/LIBRA-project/BABY-LiOx/blob/neutronics/environment.yml)

### PR DESCRIPTION
**Pull request by pshriwise**
# Description

For some context,  during the process of tracing a track segment along the mesh elements, the `PeriodicMesh::distance_to_grid_boundary` method uses the initial position as-is, while the `get_indices` transforms the initial coordinates to local coordinates by default. I'd like to change this to be something more consistent, but I'll save that for another PR.

Two problems are fixed here:

1. Coordinates were adjusted for the origin more than once in the process of calling `bins_crossed` for cylindrical meshes. They are adjusted in once `raytrace_mesh` and again in the `CylindricalMesh` implementation of `distance_to_grid_boundary`. The additional transformation in `distance_to_grid_boundary` has been removed.
2. When a particle partially overlaps the mesh, a `get_indices` call is used to determine which element the particle passes into (if it does at all). The coordinates passed have already been transformed and an additional, incorrect, transformation is applied within this method.

I've updated the `filter_mesh` regression test to use an origin with a z-value and adjusted the z grid of the original mesh to obtain an equivalent mesh with an origin. Without the changes here in `mesh.cpp` the regression results failed produced negative flux values. With the changes applied the test passes without changes to the regression results.

Fixes #3369 

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) (version 15) on any C++ source files (if applicable)
- [x] I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)

### CODE REVIEW

File: include/openmc/mesh.h [hunk 1]
```diff
@@ -427,7 +427,7 @@ class PeriodicStructuredMesh : public StructuredMesh {
   PeriodicStructuredMesh() = default;
   PeriodicStructuredMesh(pugi::xml_node node) : StructuredMesh {node} {};
 
-  void local_coords(Position& r) const override { r -= origin_; };
+  Position& local_coords(Position& r) const override { return r -= origin_; };
```
Comment (paulromano) [inline include/openmc/mesh.h:430]: I find this super confusing to have two overloads of `local_coords`, where the only difference is that one of them modifies its argument if it is not `const`. That side effect may seem surprising to a caller, who may assume that `local_coords` simply returns the position in the local coordinates. How about just having a single method with the following interface:
```C++
Position local_coords(const Position& r) const { return r - origin_; }
```
and if the caller wants to modify the value, they can do so explicitly.

**Review by paulromano — CHANGES_REQUESTED** [review]
Thanks for the PR @pshriwise. See comment below regarding the `local_coords` method:

File: include/openmc/mesh.h (hunk 1 above)
Comment (pshriwise) [reply include/openmc/mesh.h:430]: Yeah, you're right. We shouldn't have both. My only thought in favor of the in-place modification and returned reference was avoiding extra allocations, but doing some cursory tests with the `filter_mesh` regression tests it doesn't seem we are taking much of a hit there.

**Review by paulromano — APPROVED** [review]

**Comment by RemDelaporteMathurin** [comment]
@pshriwise @paulromano do we know when the next release containing this fix will be out?
