### PR TITLE
Reset DAGMC history when reviving from source.

### LINKED ISSUE #3600: Lost particles when transporting on DAGMC geometry with weight windows
## Bug Description

Assuming I'm not making any errors with my input, the `develop` branch seems to be having issues transporting on DAGMC geometries when a weight window mesh is used. Specifically, the ray firing routine has trouble finding a surface intersection, resulting in a lost particle with a warning like the following:
```
WARNING: No intersection found with DAGMC cell 1, filled with material 12
```
I suspect this is happening to new particles after splitting, but have not verified.

It's worth noting that in my testing, this issue occurs _only when a weight window mesh is used_. I cannot replicate with an analog or implicit capture run, even when bumping up the number of particles by several orders of magnitude.

I also cannot replicate the issue if using the latest release (0.15.2), with nothing else changed.

## Steps to Reproduce

I've included an input stack for a minimum-working example. Note that this stack does not include weight windows (the resultant tarball is too large) but does include two separate scripts to create some. One script uses MAGIC and the other FW-CADIS, whichever is preferred. Note that if using the `develop` branch, the MAGIC method will fail after the first batch. For FW-CADIS, a small 6-group cross-section file is included.
[spherical_shell.tar.gz](https://github.com/user-attachments/files/22754011/spherical_shell.tar.gz)

Also included is a DAGMC geometry of nested spherical shells, pictured below. The shells are filled with typical fusion materials. Note that the innermost sphere is void, illustrated in white. There is also a void gap region between the vacuum vessel and "magnets".
Image

All material definitions correspond to the tags in the DAGMC geometry. With the exception of a weight window file for `transport.py`, one should be able to use the scripts as-is. Note that the scripts only create the model XML file. One would need to execute `openmc` after executing the script. The number of particles, batches, etc. may want some tweaking for testing, though. They're unnecessarily high.

## Environment

Using the `openmc/openmc:latest-dagmc` and `openmc/openmc:develop-dagmc` Docker images.

### PR DESCRIPTION
**Pull request by pshriwise**
# Description

A particle's DAGMC history should be reset when particles are being sourced from the secondary bank. A history from a previous particle can cause incorrect intersection determination in DAGMC as any previously intersected faces in the history at the time of sourcing from the secondary bank may cause surface intersections to be erroneously ignored.

A hypothetical related to #3600 would be the following:

1. A primary particle undergoes splitting near a vacuum boundary (or exterior surface of the DAGMC model.
2. As its next event, the primary particle then exits the problem through the boundary . During this process the DAGMC triangle through which it exits is stored in the particle's DAGMC history.
3. A new particle is sourced from the secondary bank with the primary particles position at the split and direction. As a result of this identical position and direction the same triangle on the vacuum boundary is struck but ignored by nature of being in the particle's DAGMC history. Thus, an intersection is not found and the particle is considered lost.

This probably hasn't occurred very often because more splitting occurs in materials with higher collision density and collision events reset the particle history. That said, a MWE wasn't terribly difficult to construct and I'm glad to be able to address the problem.

Fixes #3600

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) (version 15) on any C++ source files (if applicable)
- [ ] I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)
- [x] ~I have made corresponding changes to the documentation (if applicable)~
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)

### CODE REVIEW

File: src/particle.cpp [hunk 1]
```diff
@@ -151,6 +151,10 @@ void Particle::from_source(const SourceSite* src)
     int index_plus_one = model::surface_map[std::abs(src->surf_id)] + 1;
     surface() = (src->surf_id > 0) ? index_plus_one : -index_plus_one;
   }
+
+#ifdef OPENMC_DAGMC_ENABLED
+  history().reset();
+#endif
```
Comment (GuySten) [inline src/particle.cpp]: I think a better place for this change should be after line 123 where the resetting attributes section is.

Comment (pshriwise) [reply src/particle.cpp]: Good observation @GuySten. Agreed. I'll move it there.

File: tests/regression_tests/dagmc/weight_windows/test.py [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+
+    def __init__(self):
+        super().__init__('')
+
+    def execute_test(self):
+        # this test merely needs to run OpenMC without error
+        try:
+            self._run_openmc()
+        finally:
+            self._cleanup()
```
Comment (paulromano) [inline tests/regression_tests/dagmc/weight_windows/test.py]: Since this test is literally just running OpenMC to make sure it completes, I don't think it really belongs in `regression_tests`. Can you 1) move it to the `unit_tests` directory and 2) construct the model using the Python API since it is simple enough? Also, is there any way we can get the .h5m file to be smaller? 57 kB is not huge but more than I would normally like to add for a new test.

Comment (pshriwise) [reply tests/regression_tests/dagmc/weight_windows/test.py]: Fair point. It does check for a regression of this particular pathology with DAGMC geometry, but you're right it doesn't really fit into the regression test suite. I've moved it into the unit tests under weight windows.

I'll think on how to reduce the size of the .h5m file but it's already about as minimal as it can get -- 3 cubes (8 vertices, 12 triangles each) with one material assignment. I could remove one of the cubes but I doubt it would change the file size substantially. Another option might be to adapt one of the other DAGMC models in the repo. However, the key to this model is that several surfaces are very close to each other, with the outer surface set with a vacuum boundary condition. The current set of DAGMC models in the repo don't meet that condition.
