### PR TITLE
Remove a search from tally mesh code

### LINKED ISSUE #820: Tally mesh filters fail for very small meshes in very big geometries
If a neutron is far away from a mesh with small cell widths, then the `get_next_bin_mesh` method can reach `MAX_SEARCH_ITER` while trying to find the cell that the particle intersects.  I didn't think this case would happen because it doesn't make sense for normal reactor calculations, but (as these things always go) there is some researcher who needs that corner case.  "Thanks" @bforget for keeping me on my toes.

We should be able to remove the search loop and just compute exactly which mesh cell the particle will intersect.  Maybe this could overload `mesh_intesects_*d` since it does most of that calculation already.

### PR DESCRIPTION
**Pull request by smharper**
Closes #820

This PR finally cleans up a bit of an expediency I took a while back when moving all the tracklength mesh tallying implementation into the `MeshFilter` object.  Currently when a track starts outside the bounds of a mesh and then enters it, the code will find the (invalid) indices for that starting position and iterate them step-by-step until we reach a valid index.  I was worried about the possibility of finite-precision errors getting us into this loop where we assume that a track intersects the mesh, but this initial walk never finds valid indices so I added a `MAX_SEARCH_ITER` which causes the #820 bug.

However, this search isn't really needed.  Immediately before running the search, we have code that computes the intersection of the track with the mesh boundaries.  This PR modifies the code so that we can reuse the information from that intersection calculation to avoid the search completely.

I ran a quick test that checks for some regressions that wouldn't be covered by our test suite:  I added 1d, 2d, and 3d meshes smaller than the overall geometry bounds to a pincell calculation.  After running 100k active particles, I find no difference in the tallies.out between this branch and the current develop branch.

### CODE REVIEW

File: src/mesh.cpp [hunk 1]
```diff
@@ -204,45 +230,72 @@ void RegularMesh::get_indices_from_bin(int bin, int* ijk) const
   }
 }
 
-bool RegularMesh::intersects(Position r0, Position r1) const
+bool RegularMesh::intersects(Position& r0, Position r1, int* ijk) const
```
Comment (paulromano) [inline src/mesh.cpp]: It seems pretty awkward to me that this method modifies the `r0` argument. I'd prefer to see either a separate argument that returns the intersection point or multiple return values via a `std::pair`.

Comment (smharper) [reply src/mesh.cpp]: Agreed that it looks a little awkward for the general use case, but it feels somewhat more natural in `RegularMesh::bins_crossed` where the old value of `r0` isn't needed after you know the intersection point.  I tried adding another `Position&` argument as the output, and it looks like it slows down the code by about 4% on the tally test we've been running.

It's worth noting that `intersects` is not used anywhere outside of mesh.cpp.  If you like, I can remove it as a method and just have it defined in mesh.cpp.  That way, anyone who wants something like `intersect` for other purposes will probably make a new method that wraps this functionality with a cleaner interface.

**Comment by smharper** [comment]
I did some timing on the same #1184 inputs for this branch vs. develop with 1 OpenMP thread (but compiled with -Dopenmp=on).  It seems to be about 4% faster (reproduced with 2 runs per branch).  That number is small enough that it could be a fluke or could disappear in different conditions, but it's better than 4% slower!  I would expect this PR to be significantly faster than develop with different inputs that use small meshes contained inside of big geometries, but I haven't tested it.

File: src/mesh.cpp (hunk 1 above)
Comment (paulromano) [reply src/mesh.cpp]: Ok, I'm fine keeping it as is. No need to worry about the interface too much until someone starts adding other mesh types :)

**Comment by paulromano** [comment]
Since this is a beyond-trivial change, I'll let it sit until tomorrow in case others have comments.
